/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package movieticket.view;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import movieticket.model.Movie;
import movieticket.model.MovieData;

/**
 *
 * @author acer
 */
public class AddandUpdate extends javax.swing.JFrame {

    /**
     * Creates new form AddandUpdate
     */
    public AddandUpdate() {
        initComponents();
         loadMoviePosters();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Poster1 = new javax.swing.JLabel();
        MovieName1 = new javax.swing.JLabel();
        TimeBtn1 = new javax.swing.JButton();
        TimeBtn2 = new javax.swing.JButton();
        Duration1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Poster2 = new javax.swing.JLabel();
        MovieName2 = new javax.swing.JLabel();
        TimeBtn3 = new javax.swing.JButton();
        TimeBtn4 = new javax.swing.JButton();
        Duration2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Poster3 = new javax.swing.JLabel();
        MovieName3 = new javax.swing.JLabel();
        TimeBtn5 = new javax.swing.JButton();
        TimeBtn6 = new javax.swing.JButton();
        Duration3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Available Movies");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        Poster1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Poster1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/smallpost.png"))); // NOI18N
        Poster1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Poster1Switchpages(evt);
            }
        });

        MovieName1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MovieName1.setForeground(new java.awt.Color(255, 255, 255));
        MovieName1.setText("Movie 1");
        MovieName1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MovieName1MouseClicked(evt);
            }
        });

        TimeBtn1.setBackground(new java.awt.Color(255, 51, 0));
        TimeBtn1.setText("9:00 AM");

        TimeBtn2.setBackground(new java.awt.Color(0, 255, 0));
        TimeBtn2.setText("10:00 AM");
        TimeBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeBtn2ActionPerformed(evt);
            }
        });

        Duration1.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        Duration1.setForeground(new java.awt.Color(255, 255, 255));
        Duration1.setText("2 hours 30 mins");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Poster1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TimeBtn1)
                                .addGap(18, 18, 18)
                                .addComponent(TimeBtn2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(MovieName1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Duration1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Poster1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MovieName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Duration1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimeBtn1)
                    .addComponent(TimeBtn2))
                .addGap(19, 19, 19))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        Poster2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Poster2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/smallpost.png"))); // NOI18N
        Poster2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Poster2Switchpages(evt);
            }
        });

        MovieName2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MovieName2.setForeground(new java.awt.Color(255, 255, 255));
        MovieName2.setText("Movie 1");
        MovieName2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MovieName2MouseClicked(evt);
            }
        });

        TimeBtn3.setBackground(new java.awt.Color(255, 51, 0));
        TimeBtn3.setText("9:00 AM");

        TimeBtn4.setBackground(new java.awt.Color(0, 255, 0));
        TimeBtn4.setText("10:00 AM");
        TimeBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeBtn4ActionPerformed(evt);
            }
        });

        Duration2.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        Duration2.setForeground(new java.awt.Color(255, 255, 255));
        Duration2.setText("2 hours 30 mins");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Poster2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TimeBtn3)
                                .addGap(18, 18, 18)
                                .addComponent(TimeBtn4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(MovieName2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Duration2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Poster2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MovieName2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Duration2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimeBtn3)
                    .addComponent(TimeBtn4))
                .addGap(19, 19, 19))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        Poster3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Poster3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/smallpost.png"))); // NOI18N
        Poster3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Poster3Switchpages(evt);
            }
        });

        MovieName3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MovieName3.setForeground(new java.awt.Color(255, 255, 255));
        MovieName3.setText("Movie 1");
        MovieName3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MovieName3MouseClicked(evt);
            }
        });

        TimeBtn5.setBackground(new java.awt.Color(255, 51, 0));
        TimeBtn5.setText("9:00 AM");

        TimeBtn6.setBackground(new java.awt.Color(0, 255, 0));
        TimeBtn6.setText("10:00 AM");
        TimeBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeBtn6ActionPerformed(evt);
            }
        });

        Duration3.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        Duration3.setForeground(new java.awt.Color(255, 255, 255));
        Duration3.setText("2 hours 30 mins");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Poster3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TimeBtn5)
                                .addGap(18, 18, 18)
                                .addComponent(TimeBtn6))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(MovieName3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Duration3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Poster3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MovieName3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Duration3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimeBtn5)
                    .addComponent(TimeBtn6))
                .addGap(19, 19, 19))
        );

        jButton1.setBackground(new java.awt.Color(255, 51, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Movies");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update Movies");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Poster1Switchpages(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Poster1Switchpages
        MovieDetails details = new MovieDetails();
        details.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_Poster1Switchpages

    private void MovieName1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovieName1MouseClicked
        MovieDetails details = new MovieDetails();
        details.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_MovieName1MouseClicked

    private void TimeBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeBtn2ActionPerformed

    private void Poster2Switchpages(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Poster2Switchpages
        // TODO add your handling code here:
    }//GEN-LAST:event_Poster2Switchpages

    private void MovieName2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovieName2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MovieName2MouseClicked

    private void TimeBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeBtn4ActionPerformed

    private void Poster3Switchpages(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Poster3Switchpages
        // TODO add your handling code here:
    }//GEN-LAST:event_Poster3Switchpages

    private void MovieName3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovieName3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MovieName3MouseClicked

    private void TimeBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeBtn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeBtn6ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    AdminMovies movies = new AdminMovies();
    movies.setVisible(true);
    this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
    AdminMovies movies = new AdminMovies();
        movies.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked
    private void loadMoviePosters() {
    for (Movie movie : MovieData.movieList) {
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.setBackground(new Color(51, 51, 51));

        JLabel poster = new JLabel();
        poster.setHorizontalAlignment(SwingConstants.CENTER);
        poster.setIcon(new ImageIcon(movie.getPosterPath())); // optional

        JLabel name = new JLabel(movie.getTitle());
        name.setForeground(Color.WHITE);
        name.setFont(new Font("Segoe UI", Font.BOLD, 12));

        JLabel duration = new JLabel(movie.getDuration());
        duration.setForeground(Color.WHITE);

        JButton time1 = new JButton("9:00 AM");
        JButton time2 = new JButton("10:00 AM");

        panel.add(poster);
        panel.add(name);
        panel.add(duration);
        panel.add(time1);
        panel.add(time2);

        getContentPane().add(panel);
    }
    revalidate();
    repaint();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddandUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddandUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddandUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddandUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddandUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Duration1;
    private javax.swing.JLabel Duration2;
    private javax.swing.JLabel Duration3;
    private javax.swing.JLabel MovieName1;
    private javax.swing.JLabel MovieName2;
    private javax.swing.JLabel MovieName3;
    private javax.swing.JLabel Poster1;
    private javax.swing.JLabel Poster2;
    private javax.swing.JLabel Poster3;
    private javax.swing.JButton TimeBtn1;
    private javax.swing.JButton TimeBtn2;
    private javax.swing.JButton TimeBtn3;
    private javax.swing.JButton TimeBtn4;
    private javax.swing.JButton TimeBtn5;
    private javax.swing.JButton TimeBtn6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
