/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package movieticket.view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.io.File;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

/**
 *
 * @author Hp
 */
public class RegistrationView extends javax.swing.JFrame {
       File selectedFile;
    /**
     * Creates new form RegistrationView
     */
    public RegistrationView() {
        initComponents();
         setTitle("Register Screen");
        setLayout(new BorderLayout());
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AppLogo = new javax.swing.JLabel();
        AppName = new javax.swing.JLabel();
        LogInHead = new javax.swing.JLabel();
        LogInsub1 = new javax.swing.JLabel();
        LogInsub2 = new javax.swing.JLabel();
        LogInBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        SignupTitle = new javax.swing.JLabel();
        SignUpSubtitle = new javax.swing.JLabel();
        NameIcon = new javax.swing.JLabel();
        txtNameField = new javax.swing.JTextField();
        EmailIcon = new javax.swing.JLabel();
        txtEmailField = new javax.swing.JTextField();
        PasswordIcon = new javax.swing.JLabel();
        txtConfirmPasswordField = new javax.swing.JPasswordField();
        txtPasswordField = new javax.swing.JPasswordField();
        PasswordIcon1 = new javax.swing.JLabel();
        UploadImageBtn = new javax.swing.JButton();
        SignUpBtn = new javax.swing.JButton();
        ShowPasswordBtn = new javax.swing.JButton();
        ShowConfirmPasswordBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(770, 460));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));

        AppLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clap.png"))); // NOI18N

        AppName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 23)); // NOI18N
        AppName.setForeground(new java.awt.Color(255, 51, 51));
        AppName.setText("PremierBox");
        AppName.setToolTipText("");
        AppName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        LogInHead.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        LogInHead.setForeground(new java.awt.Color(255, 255, 255));
        LogInHead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogInHead.setText("Already have an account?");

        LogInsub1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LogInsub1.setForeground(new java.awt.Color(204, 204, 204));
        LogInsub1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogInsub1.setText("Enter your personal details");

        LogInsub2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LogInsub2.setForeground(new java.awt.Color(204, 204, 204));
        LogInsub2.setText("and stay connected with us.");

        LogInBtn.setBackground(new java.awt.Color(0, 153, 102));
        LogInBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LogInBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogInBtn.setText("Log In");
        LogInBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        LogInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LogInHead, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AppLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AppName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LogInsub2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LogInsub1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(LogInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AppLogo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AppName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(LogInHead, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogInsub1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogInsub2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(LogInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 460));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        SignupTitle.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        SignupTitle.setForeground(new java.awt.Color(0, 128, 102));
        SignupTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignupTitle.setText("Sign Up");

        SignUpSubtitle.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        SignUpSubtitle.setForeground(new java.awt.Color(102, 102, 102));
        SignUpSubtitle.setText("Enter your personal details");

        NameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/name.png"))); // NOI18N

        txtNameField.setForeground(new java.awt.Color(153, 153, 153));
        txtNameField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFieldFocusLost(evt);
            }
        });
        txtNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameFieldActionPerformed(evt);
            }
        });

        EmailIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/email.png"))); // NOI18N

        txtEmailField.setForeground(new java.awt.Color(153, 153, 153));
        txtEmailField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtEmailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFieldFocusLost(evt);
            }
        });
        txtEmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailFieldActionPerformed(evt);
            }
        });

        PasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lock.png"))); // NOI18N

        txtConfirmPasswordField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtConfirmPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConfirmPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConfirmPasswordFieldFocusLost(evt);
            }
        });
        txtConfirmPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmPasswordFieldActionPerformed(evt);
            }
        });

        txtPasswordField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFieldFocusLost(evt);
            }
        });
        txtPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordFieldActionPerformed(evt);
            }
        });

        PasswordIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lock.png"))); // NOI18N

        UploadImageBtn.setBackground(new java.awt.Color(0, 102, 102));
        UploadImageBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UploadImageBtn.setForeground(new java.awt.Color(255, 255, 255));
        UploadImageBtn.setText("Upload Image");
        UploadImageBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        UploadImageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadImageBtnActionPerformed(evt);
            }
        });

        SignUpBtn.setBackground(new java.awt.Color(0, 153, 102));
        SignUpBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SignUpBtn.setForeground(new java.awt.Color(255, 255, 255));
        SignUpBtn.setText("Sign Up");
        SignUpBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        SignUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpBtnActionPerformed(evt);
            }
        });

        ShowPasswordBtn.setText("Show");
        ShowPasswordBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.black));
        ShowPasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPasswordBtnActionPerformed(evt);
            }
        });

        ShowConfirmPasswordBtn.setText("Show");
        ShowConfirmPasswordBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.black));
        ShowConfirmPasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowConfirmPasswordBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(SignupTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(SignUpSubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EmailIcon)
                            .addComponent(NameIcon)
                            .addComponent(PasswordIcon)
                            .addComponent(PasswordIcon1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ShowConfirmPasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ShowPasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(UploadImageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(SignUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(SignupTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignUpSubtitle)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ShowPasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ShowConfirmPasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(PasswordIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PasswordIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UploadImageBtn)
                .addGap(18, 18, 18)
                .addComponent(SignUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 460, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFieldFocusGained
        if (txtNameField.getText().equals("Email")) {
            txtNameField.setText("");
            txtNameField.setForeground(Color.BLACK);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameFieldFocusGained

    private void txtNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFieldFocusLost
        if (txtNameField.getText().trim().isEmpty()) {
            txtNameField.setText("Email");
            txtNameField.setForeground(Color.GRAY);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameFieldFocusLost

    private void txtNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameFieldActionPerformed

    private void txtEmailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFieldFocusGained
        if (txtEmailField.getText().equals("Email")) {
            txtEmailField.setText("");
            txtEmailField.setForeground(Color.BLACK);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailFieldFocusGained

    private void txtEmailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFieldFocusLost
        if (txtEmailField.getText().trim().isEmpty()) {
            txtEmailField.setText("Email");
            txtEmailField.setForeground(Color.GRAY);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailFieldFocusLost

    private void txtEmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailFieldActionPerformed

    private void txtConfirmPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmPasswordFieldFocusGained
        if (txtConfirmPasswordField.getText().equals("Password")) {
            txtConfirmPasswordField.setText("");
            txtConfirmPasswordField.setForeground(Color.BLACK);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmPasswordFieldFocusGained

    private void txtConfirmPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmPasswordFieldFocusLost
        if (txtConfirmPasswordField.getText().trim().isEmpty()) {
            txtConfirmPasswordField.setText("Password");
            txtConfirmPasswordField.setForeground(Color.GRAY);
        }   // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmPasswordFieldFocusLost

    private void txtConfirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmPasswordFieldActionPerformed

    private void txtPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFieldFocusGained
        if (txtConfirmPasswordField.getText().equals("Password")) {
            txtConfirmPasswordField.setText("");
            txtConfirmPasswordField.setForeground(Color.BLACK);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordFieldFocusGained

    private void txtPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFieldFocusLost
        if (txtConfirmPasswordField.getText().trim().isEmpty()) {
            txtConfirmPasswordField.setText("Password");
            txtConfirmPasswordField.setForeground(Color.GRAY);
        }   // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordFieldFocusLost

    private void txtPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordFieldActionPerformed

    private void UploadImageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadImageBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UploadImageBtnActionPerformed

    private void SignUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpBtnActionPerformed

    private void ShowPasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPasswordBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShowPasswordBtnActionPerformed

    private void ShowConfirmPasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowConfirmPasswordBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShowConfirmPasswordBtnActionPerformed

    private void LogInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AppLogo;
    private javax.swing.JLabel AppName;
    private javax.swing.JLabel EmailIcon;
    private javax.swing.JButton LogInBtn;
    private javax.swing.JLabel LogInHead;
    private javax.swing.JLabel LogInsub1;
    private javax.swing.JLabel LogInsub2;
    private javax.swing.JLabel NameIcon;
    private javax.swing.JLabel PasswordIcon;
    private javax.swing.JLabel PasswordIcon1;
    private javax.swing.JButton ShowConfirmPasswordBtn;
    private javax.swing.JButton ShowPasswordBtn;
    private javax.swing.JButton SignUpBtn;
    private javax.swing.JLabel SignUpSubtitle;
    private javax.swing.JLabel SignupTitle;
    private javax.swing.JButton UploadImageBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtConfirmPasswordField;
    private javax.swing.JTextField txtEmailField;
    private javax.swing.JTextField txtNameField;
    private javax.swing.JPasswordField txtPasswordField;
    // End of variables declaration//GEN-END:variables

     public void addRegisterUserListener(ActionListener listener) {
        SignUpBtn.addActionListener(listener);
    }
    public void togglePasswordField(boolean visible) {
        txtPasswordField.setEchoChar(visible ? (char) 0 : '*');
        ShowPasswordBtn.setText(visible ? "Hide" : "Show");
    }

    public void toggleConfirmPasswordField(boolean visible) {
        txtConfirmPasswordField.setEchoChar(visible ? (char) 0 : '*');
            ShowConfirmPasswordBtn.setText(visible ? "Hide" : "Show");
    }

    public void addLoginListener(MouseListener listener){
        LogInBtn.addMouseListener(listener);
    }
    
    public void showPasswordButtonListener(ActionListener listener){
        ShowPasswordBtn.addActionListener(listener);
    }
    
    public void showPasswordButton1Listener(ActionListener listener){
        ShowConfirmPasswordBtn.addActionListener(listener);
    }
    public void uploadImageButtonListener(ActionListener listener){
        UploadImageBtn.addActionListener(listener);
    }

    public void setSelectedFile(File file) {
        this.selectedFile = file;
    }
    
    public javax.swing.JTextField getNameTextField(){
        return txtNameField;
    }
    
    public javax.swing.JTextField getEmailTextField(){
        return txtEmailField;
    }
    
    public javax.swing.JPasswordField getPasswordField(){
            return txtPasswordField;
    }
    
    public javax.swing.JPasswordField getConfirmPasswordField(){
        return txtConfirmPasswordField;
    }
    
    public File getSelectedFile(){
        return selectedFile;
    }
   




}
