/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package movieticket.view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.PopupMenu;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;


/**
 *
 * @author acer
 */
public class ShowtimeBooking extends javax.swing.JFrame {


    /**
     * Creates new form ShowtimeBooking
     */
    public ShowtimeBooking() {
        initComponents();
         btnToday.addActionListener(e -> loadShowtimesForDate("Today"));
        btnTomorrow.addActionListener(e -> loadShowtimesForDate("Tomorrow"));
        loadShowtimesForDate("Today"); // Show default data

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelShowtimes = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnToday = new javax.swing.JButton();
        btnTomorrow = new javax.swing.JButton();
        panelHalls = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelShowtimes.setBackground(new java.awt.Color(0, 0, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/smallpost.png"))); // NOI18N

        btnToday.setText("Today");

        btnTomorrow.setText("Tomorrow");

        panelHalls.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hall 1");

        jButton4.setBackground(new java.awt.Color(0, 0, 102));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("9:00 AM");

        jButton5.setBackground(new java.awt.Color(0, 0, 102));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("10:00 AM");

        javax.swing.GroupLayout panelHallsLayout = new javax.swing.GroupLayout(panelHalls);
        panelHalls.setLayout(panelHallsLayout);
        panelHallsLayout.setHorizontalGroup(
            panelHallsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHallsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton4)
                .addGap(31, 31, 31)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHallsLayout.setVerticalGroup(
            panelHallsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHallsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelHallsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelShowtimesLayout = new javax.swing.GroupLayout(panelShowtimes);
        panelShowtimes.setLayout(panelShowtimesLayout);
        panelShowtimesLayout.setHorizontalGroup(
            panelShowtimesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShowtimesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelShowtimesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelHalls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelShowtimesLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 385, Short.MAX_VALUE)
                        .addComponent(btnToday)
                        .addGap(18, 18, 18)
                        .addComponent(btnTomorrow)
                        .addGap(13, 13, 13)))
                .addGap(17, 17, 17))
        );
        panelShowtimesLayout.setVerticalGroup(
            panelShowtimesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShowtimesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelShowtimesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(panelShowtimesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnToday)
                        .addComponent(btnTomorrow)))
                .addGap(18, 18, 18)
                .addComponent(panelHalls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShowtimes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShowtimes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowtimeBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowtimeBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowtimeBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowtimeBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowtimeBooking().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnToday;
    private javax.swing.JButton btnTomorrow;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelHalls;
    private javax.swing.JPanel panelShowtimes;
    // End of variables declaration//GEN-END:variables

    private void loadShowtimesForDate(String date) {
        panelHalls.removeAll();

    if (date.equals("Today")) {
        panelHalls.add(createHallPanel("Hall 1", new String[] {"9:00 AM", "10:00 AM"}));
    } else if (date.equals("Tomorrow")) {
        panelHalls.add(createHallPanel("Hall 1", new String[] {"1:00 PM", "4:00 PM"}));
        panelHalls.add(createHallPanel("Hall 2", new String[] {"11:30 AM", "3:15 PM"}));
    } 
    panelHalls.revalidate();
    panelHalls.repaint();

    }
private JPanel createHallPanel(String hallName, String[] times) {
    JPanel hallPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
    hallPanel.setBackground(new Color(8, 45, 85));
    hallPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

    JLabel label = new JLabel(hallName);
    label.setFont(new Font("Arial", Font.BOLD, 18));
    label.setForeground(Color.WHITE);
    hallPanel.add(label);

    for (String time : times) {
        JButton btn = new JButton(time);
        btn.setPreferredSize(new Dimension(100, 40));
        btn.setBackground(new Color(25, 25, 112));
        btn.setForeground(Color.WHITE);
        btn.setFocusPainted(false);
        hallPanel.add(btn);
    }

    return hallPanel;
}

}
